id: P3188A1A7
initial_creation_type: input
source_metadata:
  title: Rigdzin Nyima Drakpa
  language: fr
  description: 'Texts by and about the treasure-revealer Rigdzin Nyima Drakpa (rig
    ''dzin nyi ma grags pa, 1647–1710), alias Garwang Drodül Lingpa:'
  volume:
    4f22577d0cfa4017b037c372131fc056:
      title: 'Marmé Mönlam: The Light Offering Prayer'
      parent: Aspiration Prayers
created_at: '2022-03-01T01:22:35.008782'
last_modified_at: '2022-03-01T01:22:35.008784'
